# Generated by Django 4.1.7 on 2023-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set_stoploss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspend_option', models.CharField(choices=[('Nenhum', 'Nenhum'), ('Pontos', 'Pontos'), ('Financeiro', 'Financeiro'), ('Variação %', 'Variação %'), ('Indicador', 'Indicador')], default='Nenhum', max_length=20)),
            ],
        ),
    ]
