# Generated by Django 4.1.7 on 2023-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stoploss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
    ]
