# Generated by Django 4.1.7 on 2023-03-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0002_stoploss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set_stoploss',
        ),
    ]
