# Generated by Django 4.1.7 on 2023-03-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0003_delete_set_stoploss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stoploss',
        ),
    ]
