# Generated by Django 4.1.7 on 2023-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siteapps', '0004_delete_stoploss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoploss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
    ]
