# Generated by Django 4.1.7 on 2023-03-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0006_usr_algo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usr_algo',
            new_name='UsrAlgo',
        ),
    ]
