# Generated by Django 4.1.7 on 2023-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapps', '0007_rename_usr_algo_usralgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='name')),
                ('broker', models.CharField(max_length=65)),
                ('account', models.IntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
